# Generated by Django 4.0.6 on 2022-07-15 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.FloatField()),
                ('start_date', models.DateField()),
                ('amount_used', models.FloatField()),
                ('amount_surplus', models.FloatField()),
                ('comments', models.TextField(max_length=500)),
                ('budget', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finbalmanager.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('tax_amt', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(blank=True, max_length=50)),
                ('order_ref_no', models.CharField(blank=True, max_length=50)),
                ('trn_ref_no', models.CharField(blank=True, max_length=50)),
                ('comments', models.CharField(max_length=500)),
                ('budget_detail', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finbalmanager.budgetdetails')),
                ('expense', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finbalmanager.expense')),
            ],
        ),
        migrations.CreateModel(
            name='EarningDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('tax_amt', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(blank=True, max_length=50)),
                ('order_ref_no', models.CharField(blank=True, max_length=50)),
                ('trn_ref_no', models.CharField(blank=True, max_length=50)),
                ('comments', models.CharField(max_length=500)),
                ('budget_detail', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finbalmanager.budgetdetails')),
                ('earning', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finbalmanager.earning')),
            ],
        ),
    ]
